# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f5036d4c6f9eb455577751b22e0973f071a22d2a5f82a3d9f136851e2c1fabdf477f04b84744d14433f3e19442072e1d36de02e9122141eb421c321e6c2befd

test:
  secret_key_base: a1cd1684307cc8879c1847334940b7857930782158f480d91d456e6f12cecc46115ddd2fb073b5e9404b18ffaf30189edc71b2667154b3fdb5d6542dfb6287e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
